version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 5000:5000
    volumes:
      - ./web-files:/app
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - SECRET_KEY
    depends_on:
      - db
    entrypoint: /entrypoint.sh


  db:
    image: postgres:latest
    restart: always
    container_name: postgres
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petsite
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
