"""empty message

Revision ID: 104778be3f6c
Revises: 3ee22ef9e31c
Create Date: 2023-07-24 09:49:22.223854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '104778be3f6c'
down_revision = '3ee22ef9e31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
