"""empty message

Revision ID: 18f580390052
Revises: 
Create Date: 2023-07-15 16:44:34.562265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f580390052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialities',
    sa.Column('spec_id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('spec_id'),
    sa.UniqueConstraint('specialty')
    )
    op.create_table('types',
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('type'),
    sa.UniqueConstraint('type')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['type'], ['types.type'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mail')
    )
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['type'], ['types.type'], ),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('editors',
    sa.Column('editor_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['type'], ['types.type'], ),
    sa.PrimaryKeyConstraint('editor_id')
    )
    op.create_table('owners',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('owner_id')
    )
    op.create_table('vets',
    sa.Column('vet_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('spec_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['spec_id'], ['specialities.spec_id'], ),
    sa.ForeignKeyConstraint(['type'], ['types.type'], ),
    sa.PrimaryKeyConstraint('vet_id')
    )
    op.create_table('pets',
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('species', sa.String(length=50), nullable=True),
    sa.Column('breed', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.Column('medical_condition', sa.String(length=50), nullable=True),
    sa.Column('current_treatment', sa.String(length=50), nullable=True),
    sa.Column('recent_vaccination', sa.Date(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('visits',
    sa.Column('visit_id', sa.Integer(), nullable=False),
    sa.Column('vet_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.String(length=100), nullable=True),
    sa.Column('treatment', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.owner_id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.pet_id'], ),
    sa.ForeignKeyConstraint(['vet_id'], ['vets.vet_id'], ),
    sa.PrimaryKeyConstraint('visit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visits')
    op.drop_table('pets')
    op.drop_table('vets')
    op.drop_table('owners')
    op.drop_table('editors')
    op.drop_table('admins')
    op.drop_table('persons')
    op.drop_table('types')
    op.drop_table('specialities')
    # ### end Alembic commands ###
