"""empty message

Revision ID: 5797562d444d
Revises: 18f580390052
Create Date: 2023-07-15 17:02:27.583998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5797562d444d'
down_revision = '18f580390052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('types', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
