"""empty message

Revision ID: 67790253e6f1
Revises: 104778be3f6c
Create Date: 2023-07-25 06:14:06.319853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67790253e6f1'
down_revision = '104778be3f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_constraint('admins_type_fkey', type_='foreignkey')
        batch_op.drop_column('type')

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.drop_constraint('editors_type_fkey', type_='foreignkey')
        batch_op.drop_column('type')

    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.drop_constraint('vets_type_fkey', type_='foreignkey')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vets_type_fkey', 'types', ['type'], ['type'])

    with op.batch_alter_table('editors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('editors_type_fkey', 'types', ['type'], ['type'])

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('admins_type_fkey', 'types', ['type'], ['type'])

    # ### end Alembic commands ###
